apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 9c-odin-libplanet4-test-20240104
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/planetarium/9c-infra.git
    targetRevision: main
    path: charts/9c-network
    helm:
      valueFiles:
        - ../../9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: 9c-odin-libplanet4-test-20240104
