clusterName: "9c-internal-v2"
logLevel: "debug"

heimdall:
  enabled: false

alfheim:
  enabled: true

  global:
    genesisBlockPath: "https://planets.nine-chronicles.com/planets/0x000000000001/genesis"

    peerStrings:
    - "029fd8f05609cd98f716ca5245a1ebb85ab52289f9499e8453fa367bded66a945c,tcp-seed-1.alfheim.svc.cluster.local,31234"

    trustedAppProtocolVersionSigner: "030ffa9bd579ee1503ce008394f687c182279da913bfaec12baca34e79698a7cd1"

  snapshot:
    resources:
      requests:
        cpu: 1300m
        memory: 20Gi

    nodeSelector: {}

  seed:
    hosts:
    - "tcp-seed-1.alfheim.svc.cluster.local"

    nodeSelector:
      node.kubernetes.io/instance-type: m5d.xlarge

  validator:
    consensusSeedStrings:
    - "029fd8f05609cd98f716ca5245a1ebb85ab52289f9499e8453fa367bded66a945c,tcp-seed-1.alfheim.svc.cluster.local,31235"

    hosts:
    - "alfheim-internal-validator-1.nine-chronicles.com"

    resources:
      requests:
        cpu: 2
        memory: 20Gi
    
    nodeSelector: {}

  remoteHeadless:
    hosts:
    - "alfheim-internal-rpc-1.nine-chronicles.com"

    resources:
      requests:
        cpu: 1
        memory: 12Gi

    nodeSelector:
      eks.amazonaws.com/nodegroup: 9c-internal-r6g_l_2c

global:
  image:
    repository: planetariumhq/ninechronicles-headless
    tag: "git-d1edd2ded2f26c93ad340dd9a7289230b7e4c61a"

  appProtocolVersion: "200071/AB2da648b9154F2cCcAFBD85e0Bc3d51f97330Fc/MEUCIQCjmCK+qUHtgiVfmFIO+uBw.mI4Kpj9T20U4xdIK8I+MgIgSZPL7qAAplhILfRgXwUSDjjfQgQ7A8jgGNqzwDe+h3I=/ZHU5OnRpbWVzdGFtcHUxMDoyMDIzLTA5LTAxZQ=="

  iceServers:
    - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us.planetarium.dev:3478"
