clusterName: "9c-internal-v2"
logLevel: "debug"

heimdall:
  enabled: false

alfheim:
  enabled: true

  genesisBlockPath: "https://release.nine-chronicles.com/genesis-block-9c-main"

  image:
    repository: planetariumhq/ninechronicles-headless
    tag: "git-7c0815d08cb5d94700918ca4598ae2634c26ac1e"
    
  peerStrings:
  - "029fd8f05609cd98f716ca5245a1ebb85ab52289f9499e8453fa367bded66a945c,tcp-seed-1.heimdall.svc.cluster.local,31234"
  
  snapshot:
    resources:
      requests:
        cpu: 1300m
        memory: 20Gi

    nodeSelector: {}

  seed:
    hosts:
    - "tcp-seed-1.heimdall.svc.cluster.local"

    nodeSelector:
      node.kubernetes.io/instance-type: m5d.xlarge

  validator:
    consensusSeedStrings:
    - "029fd8f05609cd98f716ca5245a1ebb85ab52289f9499e8453fa367bded66a945c,tcp-seed-1.heimdall.svc.cluster.local,31235"

    hosts:
    - "heimdall-internal-validator-1.nine-chronicles.com"

    resources:
      requests:
        cpu: 2
        memory: 20Gi
    
    nodeSelector: {}

  remoteHeadless:
    hosts:
    - "heimdall-internal-rpc-1.nine-chronicles.com"

    resources:
      requests:
        cpu: 1
        memory: 12Gi

    nodeSelector:
      eks.amazonaws.com/nodegroup: 9c-internal-r6g_l_2c

global:
  image:
    repository: planetariumhq/ninechronicles-headless
    tag: "git-7c0815d08cb5d94700918ca4598ae2634c26ac1e"

  appProtocolVersion: "200010/AB2da648b9154F2cCcAFBD85e0Bc3d51f97330Fc/MEQCIAUCNU9yTZk4onxrkT8uxdfB3XFRfpxEyGzbj9BZTBlpAiBT987Kgqxnbg7yvyRn86w2c3j6.KtNsWwGKveBxMgTzw==/ZHU4OmxhdW5jaGVydTQyOjEvZGZkNTI1MDQ3Yjc4ZWY4NjNmOGFkMzJkMDIzZjk0ZjBhZTU5YmI3ZXU2OnBsYXllcnU0MjoyL2Q3MjA2OGEwODEwZjcyYzg5MDE2MzQ0N2I5YjRkYjg2NjMzYWE0ZTJ1OTp0aW1lc3RhbXB1MTA6MjAyMy0wNS0wNGU="
  trustedAppProtocolVersionSigner: "030ffa9bd579ee1503ce008394f687c182279da913bfaec12baca34e79698a7cd1"

  iceServers:
    - "turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us.planetarium.dev:3478"
