{{ if .Values.ninechroniclesUtilBackend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ninechronicles-util-backend
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: ninechronicles-util-backend
  namespace: {{ $.Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ninechronicles-util-backend
  template:
    metadata:
      labels:
        app: ninechronicles-util-backend
    spec:
      containers:
        - image: {{ $.Values.ninechroniclesUtilBackend.image.repository }}:{{ $.Values.ninechroniclesUtilBackend.image.tag }}
          name: ninechronicles-util-backend
          env:
            - name: StateService__HeadlessEndpoint
              value: {{ $.Values.ninechroniclesUtilBackend.headlessEndpoint }}
            - name: DataProvider__Endpoint
              value: {{ $.Values.ninechroniclesUtilBackend.dataProviderEndpoint }}
            - name: ASPNETCORE_URLS
              value: http://*:3000
            {{- if .Values.ninechroniclesUtilBackend.jwt.enabled }}
            - name: StateService__JwtSecretKey
              valueFrom:
                secretKeyRef:
                  key: jwt-secret-key
                  name: ninechronicles-util-backend
            - name: StateService__JwtIssuer
              valueFrom:
                secretKeyRef:
                  key: jwt-issuer
                  name: ninechronicles-util-backend
            {{- end }}
      {{- with $.Values.ninechroniclesUtilBackend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ninechronicles-util-backend
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Environment={{- if eq $.Values.clusterName "9c-main-v2" }}production{{- else }}development{{- end }},Team=game,Owner=dogeon,Service=ninechronicles-util-backend,Name=ninechronicles-util-backend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: https
      port: 443
      targetPort: 3000
  selector:
    app: ninechronicles-util-backend
  type: LoadBalancer
  externalTrafficPolicy: Local
{{ end }}
