{{ if .Values.testDataProvider.enabled }}
{{ if .Values.externalSecret.enabled }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: test-data-provider
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Release.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: test-data-provider
    creationPolicy: Owner
  dataFrom:
  - extract:
      {{- if .Values.externalSecret.prefix }}
      key: {{ .Values.externalSecret.prefix }}/test-data-provider
      {{- else }}
      key: {{ .Values.clusterName }}/test-data-provider
      {{- end }}
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: test-data-provider
  namespace: {{ $.Release.Name }}
stringData:
  database: {{ .Values.testDataProvider.db.database }}
  read-host: {{ .Values.testDataProvider.db.readHost }}
  read-value: {{ .Values.testDataProvider.db.readValue }}
  write-host: {{ .Values.testDataProvider.db.writeHost }}
  write-value: {{ .Values.testDataProvider.db.writeValue }}
  port: {{ .Values.testDataProvider.db.port }}
  user: {{ .Values.testDataProvider.db.user }}
  token: {{ .Values.testDataProvider.db.token }}
type: Opaque
{{ end }}
{{ end }}
