{{ if .Values.ninechroniclesUtilBackend.jwt.enabled }}
{{ if .Values.externalSecret.enabled }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: ninechronicles-util-backend
  namespace: {{ $.Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ $.Release.Name }}-secretsmanager
    kind: SecretStore
  target:
    name: ninechronicles-util-backend
    creationPolicy: Owner
  dataFrom:
  - extract:
      {{- if .Values.externalSecret.prefix }}
      key: {{ .Values.externalSecret.prefix }}/ninechronicles-util-backend
      {{- else }}
      key: {{ .Values.clusterName }}/ninechronicles-util-backend
      {{- end }}
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: ninechronicles-util-backend
  namespace: {{ $.Release.Name }}
stringData:
  database: {{ .Values.ninechroniclesUtilBackend.jwt.secret_key }}
  read-host: {{ .Values.ninechroniclesUtilBackend.jwt.issuer }}
type: Opaque
{{ end }}
{{ end }}
