{{ range $.Values.network }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ . }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/planetarium/9c-infra.git
    targetRevision: test/multi
    path: charts/all-in-one
    helm:
      valueFiles:
        - "../../{{ $.Values.path }}/network/general.yaml"
        - "../../{{ $.Values.path }}/network/{{ . }}.yaml"

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ . }}
---
{{ end }}
